### ISSUE TITLE
Commands fail on first start after updating image

### ISSUE THREAD

**Issue by ReenigneArcher** [LizardByte/discord-bot#38]
### Describe the Bug

After updating docker image, slash commands fail at first. After a container restart the commands seem to succeed fine.

```txt
py-cord version: 2.0.0b3

Logged in as || name: RetroArcher Bot || id: redacted

Servers connected to: [<Guild id=804382334370578482 name='RetroArcher' shard_id=0 chunked=True member_count=659>]

RetroArcher

Ignoring exception in on_interaction

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 731, in process_application_commands

    command = self._application_commands[interaction.data["id"]]

KeyError: '961389819064377346'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event

    await coro(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 1041, in on_interaction

    await self.process_application_commands(interaction)

  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 748, in process_application_commands

    await self.sync_commands(unregister_guilds=[guild_id])

  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 686, in sync_commands

    await self.http.bulk_upsert_command_permissions(

  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 338, in request

    raise HTTPException(response, data)

discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body

In 0: Invalid application command id provided

py-cord version: 2.0.0b3

Logged in as || name: RetroArcher Bot || id: redacted

Servers connected to: [<Guild id=804382334370578482 name='RetroArcher' shard_id=0 chunked=True member_count=659>]

RetroArcher
```

### Expected Behavior

Self explanatory, bot should work on first start.

### Additional Context

![image](https://user-images.githubusercontent.com/42013603/162092422-9df40acc-e5e7-4434-96be-162cbcc4b7b0.png)

**Comment by ReenigneArcher** [comment]
Closing as I don't believe this is still occurring.
